# Generated by Django 3.0.9 on 2020-11-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SavePost',
        ),
    ]
