# Generated by Django 3.0.9 on 2020-11-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_comments_likes_notification_post_savepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
