# Generated by Django 3.0.9 on 2020-11-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationOwner', models.CharField(max_length=20)),
                ('NotificationOwnerId', models.IntegerField()),
                ('NotificationType', models.CharField(max_length=20)),
                ('NotificationSentBy', models.CharField(max_length=20)),
                ('NotificationPostId', models.IntegerField()),
                ('NotificationTime', models.DateTimeField(auto_now_add=True)),
                ('NotificationStatus', models.BooleanField()),
            ],
        ),
    ]
